package algonquin.cst2335.finalproject.CurrencyConvert.Data;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Represents a currency conversion record.
 * <p>
 * This entity class holds details about a currency conversion operation, including source and destination
 * currency, original and converted amounts, exchange rate, and the date of conversion.
 * </p>
 *
 * <p>
 * The class is annotated with {@code @Entity} to specify that it represents a table in the Room database.
 * Each instance corresponds to a row in the table.
 * </p>
 */
@Entity
public class Conversion {

    /**
     * Unique ID for the conversion record.
     * This field is auto-generated by the Room database.
     */
    @PrimaryKey(autoGenerate = true)
    private int id;

    /** The currency from which the conversion originates. */
    private String sourceCurrency;

    /** The target currency for the conversion. */
    private String destinationCurrency;

    /** The original amount in the source currency. */
    private double originalAmount;

    /** The resulting amount in the destination currency after conversion. */
    private double convertedAmount;

    /** The exchange rate used for the conversion. */
    private String exchangeRate;

    /** The date of the conversion. */
    private String date;

    /**
     * Constructs a Conversion object.
     *
     * @param sourceCurrency The source currency.
     * @param destinationCurrency The destination currency.
     * @param originalAmount The original amount to be converted.
     * @param convertedAmount The converted amount in destination currency.
     * @param exchangeRate The rate used for conversion.
     * @param date The date when the conversion was performed.
     */
    public Conversion(String sourceCurrency, String destinationCurrency, double originalAmount, double convertedAmount, String exchangeRate, String date) {
        this.sourceCurrency = sourceCurrency;
        this.destinationCurrency = destinationCurrency;
        this.originalAmount = originalAmount;
        this.convertedAmount = convertedAmount;
        this.exchangeRate = exchangeRate;
        this.date = date;
    }

    // Getters
    public int getId() {
        return id;
    }

    public String getSourceCurrency() {
        return sourceCurrency;
    }

    public String getDestinationCurrency() {
        return destinationCurrency;
    }

    public double getOriginalAmount() {
        return originalAmount;
    }

    public double getConvertedAmount() {
        return convertedAmount;
    }

    public String getExchangeRate() {
        return exchangeRate;
    }

    public String getDate() {
        return date;
    }

    // Setters
    public void setId(int id) {
        this.id = id;
    }

    public void setSourceCurrency(String sourceCurrency) {
        this.sourceCurrency = sourceCurrency;
    }

    public void setDestinationCurrency(String destinationCurrency) {
        this.destinationCurrency = destinationCurrency;
    }

    public void setOriginalAmount(double originalAmount) {
        this.originalAmount = originalAmount;
    }

    public void setConvertedAmount(double convertedAmount) {
        this.convertedAmount = convertedAmount;
    }

    public void setExchangeRate(String exchangeRate) {
        this.exchangeRate = exchangeRate;
    }

    public void setDate(String date) {
        this.date = date;
    }
}
